### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/gos-website#49]

**Comment by WengerK** [comment]
This is a Frontend issue with the NextJS server. I don't know why it's slow I don't work with Next technology most of the time - I'm on the backend side of project :/

**Comment by WengerK** [comment]
Because the Docker website container is not able to curl/call the Docker Drupal container. Therefore the SSR wait 30s (http timeout) and then fallback to a standard client call.

It's due to missconfiguration of Bolo Server.

Therefore, to bypass this problem (and because it seems too complicate for Bolo to fix this infrastructure issue) I decided to add a custom host_setup script which I only run on Bolo server.
This script will add the Docker Drupal container IP with proper Domain (ex staging is staging-gos.museebolo.ch) to avoid the Docker website container attempting to go outside it's own network.

# what we try before

I try to update the host file of host-docker server with `127.0.0.1 staging-gos.museebolo.ch` but this would force use to update the `.env` by using port number (as we are local now) and whitout https (because we are local too) `NEXT_PUBLIC_ELASTICSEARCH=http://staging-api-gos.museebolo.ch:8088/search`. This lead to a configuration that can't works client side :/
